remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Terraform Associate Practice
description: Comprehensive hands-on exercises for Terraform Associate certification covering AWS and GCP providers
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/iButcat/terraform-associate-practice
  zip_url: https://github.com/iButcat/terraform-associate-practice/archive/main.zip
  tar_url: https://github.com/iButcat/terraform-associate-practice/archive/main.tar.gz 